name: Linter
on: 
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3

    - name: Install pylint
      run: pip install pylint

    - name: Running linter.py with custom .pylintrc
      run: python linter.py
      continue-on-error: false
